name: Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)